CREATE TABLE `person` (
  `Id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `Gender` VARCHAR(45) NULL DEFAULT NULL,
)
ENGINE = InnoDB;

ALTER TABLE PERSON CHANGE ID ID INT(10) AUTO_INCREMENT PRIMARY KEY;